Vagrant.configure(2) do |config|

  N = 2
  (1..N).each do |i|
    config.vm.define "haproxy#{i}" do |node|
      node.vm.box = "bento/ubuntu-18.04"
      node.vm.synced_folder ".", "/vagrant", disabled: true
      node.vm.hostname = "haproxy#{i}"
      node.vm.network "private_network", ip:"10.0.26.20#{i}"
      node.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.name = "haproxy#{i}"
      end
      node.vm.provision "shell", path: "shell/iptables.sh"
      node.vm.provision "shell", inline: "service networking restart"
      node.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
      node.vm.provision "file", source: "provision", destination: "/home/vagrant/"
    end
  end

  (1..N).each do |i|
    config.vm.define "web#{i}" do |app|
      app.vm.network "private_network", ip:"10.0.26.10#{i}"
      app.vm.hostname = "app#{i}"
      app.vm.box = "bento/ubuntu-18.04"
      app.vm.synced_folder ".", "/vagrant", disabled: true
      app.vm.box_check_update = false
      app.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.name = "web#{i}"
      end
      app.vm.provision "shell", path: "shell/iptables.sh"
      app.vm.provision "shell", inline: "service networking restart"
      app.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
      app.vm.provision "file", source: "provision", destination: "/home/vagrant/"

  end
end

end
