Vagrant.configure(2) do |config|

  N = 2
  (0..N).each do |i|
    config.vm.define "server#{i}" do |server|
      server.vm.box = "bento/ubuntu-18.04"
      server.vm.synced_folder ".", "/vagrant", disabled: true
      server.vm.hostname = "server#{i}"
      server.vm.network "private_network", ip:"10.0.36.5#{i}"
      server.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.name = "server#{i}"
      end
      server.vm.provision "shell", inline: "service networking restart"
      server.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
      server.vm.provision "file", source: "provision", destination: "/home/vagrant/"
    end
  end

   config.vm.define "client" do |client|
      client.vm.network "private_network", ip:"10.0.36.53"
      client.vm.hostname = "client"
      client.vm.box = "bento/ubuntu-18.04"
      client.vm.synced_folder ".", "/vagrant", disabled: true
      client.vm.box_check_update = false
      client.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.name = "client"
      end
      client.vm.provision "shell", inline: "service networking restart"
      client.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
      client.vm.provision "file", source: "provision", destination: "/home/vagrant/"
    end

end
