---

- name: "make sure the {{ ca_certs_dir }} is present"
  file:
    state: directory
    path: "{{ ca_certs_dir }}"
    owner: root
    group: root
    mode: 0755

- name: "Generate Certs and keys for Webservers"
  shell: 'openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout "{{ item }}".key -out "{{ item }}".crt -subj "/C=ES/ST=Spain/L=Barcelona/O=Test/OU=IT/CN="{{ item }}"/emailAddress=ca-admin@"{{ item }}""'
  args:
    chdir: "{{ ca_certs_dir }}"
  with_inventory_hostnames: webha 

- name: "Generate Certs and keys for Strongswan IKEv2"
  shell: 'openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout "{{ item }}"-key.pem -out "{{ item }}"-cert.pem -subj "/C=ES/ST=Spain/L=Barcelona/O=Test/OU=IT/CN="{{ item }}"/emailAddress=ca-admin@"{{ item }}""'
  args:
    chdir: "{{ ca_certs_dir }}"
  with_inventory_hostnames: strongswang

- name: "Generate DH param... (please wait)"
  shell: 'openssl dhparam -out dhparam.pem 1024'
  args:
    chdir: "{{ ca_certs_dir }}"
  
