---
- name: "copy keys from CA server to webha ansible template directory"
  fetch: src="{{ ca_certs_dir }}/{{ item }}.key" dest="{{ webha_distribution_certs_dir }}/{{ item }}.key.j2" flat=yes
  with_inventory_hostnames: webha

- name: "copy certs from CA server to webha ansible template directory"
  fetch: src="{{ ca_certs_dir }}/{{ item }}.crt" dest="{{ webha_distribution_certs_dir }}/{{ item }}.crt.j2" flat=yes
  with_inventory_hostnames: webha

- name: "copy keys from CA server to strongswan ansible template directory"
  fetch: src="{{ ca_certs_dir }}/{{ item }}-cert.pem" dest="{{ ss_distribution_certs_dir }}/{{ item }}-cert.pem.j2" flat=yes
  with_inventory_hostnames: strongswang

- name: "copy certs from CA server to strongswan ansible template directory"
  fetch: src="{{ ca_certs_dir }}/{{ item }}-key.pem" dest="{{ ss_distribution_certs_dir }}/{{ item }}-key.pem.j2" flat=yes
  with_inventory_hostnames: strongswang

- name: "copy DH param from server to ansible machine for distribution"
  fetch: src="{{ ca_certs_dir }}/dhparam.pem" dest="{{ webha_distribution_certs_dir }}/dhparam.pem.j2" flat=yes

- name: "copy ca.pem to strongswan ansible template directory"
  fetch: src="{{ ca_certs_dir }}/{{ item }}" dest="{{ ss_distribution_certs_dir }}/{{ item }}" flat=yes
  with_items:
  - "{{ ca_cert }}"

- name: "copy ca.pem and ca-priv-key.pem to keys_n_certs directory"
  fetch: src="{{ ca_certs_dir }}/{{ item }}" dest="{{ ss_distribution_certs_dir }}/{{ item }}" flat=yes
  with_items:
  - "{{ ca_cert }}"
  - "{{ ca_key }}"
