Vagrant.configure(2) do |config|

  config.vm.define "strongswan" do |strongswan|
      strongswan.vm.network "private_network", ip:"10.0.16.50"
      strongswan.vm.hostname = "strongswan"
      strongswan.vm.box = "bento/ubuntu-18.04"
      strongswan.vm.synced_folder ".", "/vagrant", disabled: true
      strongswan.vm.box_check_update = false
      strongswan.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.name = "strongswan"
      end
      strongswan.vm.provision "shell", inline: "service networking restart"
      strongswan.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
      strongswan.vm.provision "file", source: "provision", destination: "/home/vagrant/"
      strongswan.vm.provision "shell", path: "shell/ansible-setup.sh"
  end
end
