---

- name: "Template ipsec.conf"
  template:
    src: "ipsec.conf.j2"
    dest: "{{ vpn_ikev2_ipsec_conf_path }}"
  notify: restart strongswan

- name: "Copy server certificate"
  copy:
    src: "{{ playbook_dir }}/../roles/strongswan/templates/{{ vpn_ikev2_server_certificate_file_name }}.j2"
    dest: "{{ vpn_ikev2_server_certificate_file_path }}/{{ vpn_ikev2_server_certificate_file_name }}" 
    owner: root
    group: root
    mode: '0644'
  notify: restart strongswan
  
- name: "Copy server private key"
  copy:
    src: "{{ playbook_dir }}/../roles/strongswan/templates/{{ vpn_ikev2_server_private_key_file_name }}.j2"
    dest: "{{ vpn_ikev2_server_private_key_file_path }}/{{ vpn_ikev2_server_private_key_file_name }}"
    owner: root
    group: root
    mode: '0644'
  notify: restart strongswan

- name: "Template ipsec.secrets"
  template:
    src: "ipsec.secrets.j2"
    dest: "{{ vpn_ikev2_ipsec_secrets_path }}"
    mode: "0600"
  no_log: True
  notify: restart strongswan

